### ISSUE TITLE
we have a strange position of notification dialog on the navbar

### ISSUE THREAD

**Issue by tarzanpasha** [tookit/vue-material-admin#39]
Hi! It's very strange. We cloned this project and have the offset of notification at the navbar like in the picture.
![offset](https://user-images.githubusercontent.com/9463063/52140651-5e2b6c80-2664-11e9-913c-d834610d4786.png)

![offset2](https://user-images.githubusercontent.com/9463063/52140739-9d59bd80-2664-11e9-8bc8-298e0e71c3db.png)

what can it be?

**Comment by Absenzium-Mirror** [comment]
i have the same problem

**Comment by tarzanpasha** [comment]
> top ri

we get only
![offset5](https://user-images.githubusercontent.com/9463063/52199236-91454a00-2876-11e9-91e4-a368fd2603d7.png)
but author has 
![offset6](https://user-images.githubusercontent.com/9463063/52199326-d1a4c800-2876-11e9-878b-13ec5ebb0387.png)

**Comment by contactjavas** [comment]
I also experienced this.

If we look at @tarzanpasha image above,

- The GitHub icon looks smaller 
- The hire me button is in black. 
- And if you `yarn run serve` this master branch, you will find the searchbar is not well aligned (not in the middle, too top) with the topbar.

That is different result compared to the demo here: http://vma.isocked.com

And when trying `yarn run buid`, some assets are not builded because the those assets size is too large.

**Comment by MarcosRomeroA** [comment]
> I also experienced this.
> 
> If we look at @tarzanpasha image above,
> 
> * The GitHub icon looks smaller
> * The hire me button is in black.
> * And if you `yarn run serve` this master branch, you will find the searchbar is not well aligned (not in the middle, too top) with the topbar.
> 
> That is different result compared to the demo here: http://vma.isocked.com
> 
> And when trying `yarn run buid`, some assets are not builded because the those assets size is too large.

I have the same problems.

**Comment by tookit** [comment]
let me double check

**Comment by mjsunny** [comment]
change 
`breadcrumbs.push(item.title); 
breadcrumbs.push(child.title);` 
to
`breadcrumbs.push({text: item.title});
breadcrumbs.push({text: child.title});`
